### ISSUE TITLE
Алгоритм сопоставления с образцом

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/tiny-refal#8]
Эта задача зависит от задач

* #5
* #6

-----------

Алгоритм, описанный здесь, очень простой и очень неэффективный. Эффективный алгоритм (описанный, например, [здесь](http://refal.ru/chap2_r5.html#2.5.%20%D0%90%D0%9B%D0%93%D0%9E%D0%A0%D0%98%D0%A2%D0%9C%20%D0%A1%D0%9E%D0%9F%D0%9E%D0%A1%D0%A2%D0%90%D0%92%D0%9B%D0%95%D0%9D%D0%98%D0%AF%20%D0%A1%20%D0%9E%D0%91%D0%A0%D0%90%D0%97%D0%A6%D0%9E%D0%9C)) для представления поля зрения в виде простой строки толку будет давать мало, т.к. парные скобки всё равно надо будет подсчитывать. Но на данный момент задача реализации более быстрого представления поля зрения для нас не актуальна.

Реализация
========

Алгоритм должен быть представлен функцией

```javascript
fuction match(expr, expr_pos, pattern, pattern_pos, known_vars) {
    …
}
```
где
* `expr` (строка) — выражение, подлежащее сопоставлению,
* `expr_pos` (число) — текущая позиция в выражении,
* `pattern` (массив токенов) — массив токенов образцовой части предложения,
* `pattern_pos` (число) — текущая позиция в образце,
* `known_vars` (`Object`) — ассоциативный массив уже известных переменных, отображает имена переменных на значения.

Возвращаемым значением функции является объект с атрибутом `ok`. Если `ok === true`, то сопоставление удалось и объект является ассоциативным массивом и хранит в себе значения переменных. Если `ok === false`, то сопоставление не удалось.

Расширение ассоциативных массивов и прототипное наследование
------------------------------------------------------------------------------
Небольшое отступление. Если у нас есть ассоциативный массив
```javascript
x = { 'a': 1, 'b': 2 }
```
и мы хотим создать новый массив с теми же значениями, что есть в `x`, но при этом добавлена пара `'c': 3`, то можно сделать так:
```javascript
y = { __proto__: x, 'c': 3 }
```
Тогда в объекте `y` будет видно как поле `'c'`, так и поля `'a'` и `'b'`:
```javascript
console.log(y['a']); // 1
console.log(y['b']); // 2
console.log(y['c']); // 3
```
Этим механизмом предлагается пользоваться в рекурсивных вызовах алгоритма сопоставления

Собственно, сам алгоритм
-------------------------------
Алгоритм работает в цикле, при сопоставлении с переменными делает рекурсивный вызов.

Среди токенов образца могут быть символы, круглые скобки и переменные. Переменные отличаются от символов и скобок тем, что их длина равна `2` (токен `'t'` — буква `t`, токен `tx` — переменная _t<sub>x</sub>_).

* Если и строка, и образец дочитаны до конца:
  ```javascript
  expr.length == expr_pos && pattern.length == pattern_pos
  ```
  то алгоритм успешно завершается:
  ```javascript
  return { ok: true, __proto__: known_vars };
  ```
* Иначе, если дочитан до конца только образец:
  ```javascript
  pattern.length == pattern_pos
  ```
  результат сопоставления неуспешен:
  ```
  return { ok: false };
  ```
* Если в текущей позиции образца находится символ либо скобка (`pattern[pattern_pos].length == 1`),
  * и в текущей позиции выражения находится тоже самое, то увеличиваем обе позиции (`expr_pos` и `pattern_pos`) на `1` и переходим к следующему витку цикла,
  * иначе, если там находится что-то другое — результат сопоставления неуспешен (возвращается `{ ok: false }`).
* Если в текущей позиции образца находится переменная (`pattern[pattern_pos].length == 2`) и эта переменная уже известна (`known_vars[pattern[pattern_pos]] != undefined`), то
  * если выражение начинается со значения `known_vars[pattern[pattern_pos]]`, то увеличиваем `pattern_pos` на `1`, а `expr_pos` — на длину значения переменной и переходим к следующему витку цикла,
  * иначе — результат сопоставления неуспешен.
* Если в текущей позиции образца находится s-переменная,
  * а в текущей позиции выражения — символ (т.е. любой знак, не равный `'('` или `')'` — под символами мы понимаем любые знаки, кроме структурных скобок), рекурсивно вызываем алгоритм с увеличением позиций в выражении и образце на 1 и пополнением известных переменных значением этой переменной:
    ```javascript
    val variable = pattern[pattern_pos];
    val value = expr[expr_pos];
    return match(expr, expr_pos + 1, pattern, pattern_pos + 1, { variable: value, __proto__: known_vars };
    ```
  * иначе (в текущей позиции любая круглая скобка) — разбор неуспешен.
* Если в текущей позиции находится t-переменная
  * если в текущей позиции находится символ (т.е. не скобка) — действуем аналогично разбору s-переменной (см. выше),
  * если в текущей позиции находится открывающая скобка `'('`, то находим парную ей закрывающую скобку (алгоритм сами напишете), кладём её позицию в переменную `close_bracket` и рекурсивно вызываем алгоритм сопоставления:
    ```javascript
    val variable = pattern[pattern_pos];
    val value = expr.substr(expr_pos, close_bracket - expr_pos + 1);
    return match(expr, close_bracket + 1, pattern, pattern_pos + 1, { variable: value, __proto__: known_vars };
    ```
  * иначе если в текущей позиции находится закрывающая скобка — разбор неуспешен.
* Если в текущей позиции находится e-переменная, то начинается самое интересное — вложенный цикл.
  * устанавливаем переменную `end` на позицию перед текущей позицией в выражении:
    ```javascript
    val end = expr_pos - 1
    ```
  * цикл:
    * Рекурсивно вызываем алгоритм сопоставления, положив в e-переменную участок выражения от `expr_pos` до `end`:
      ```javascript
      val variable = pattern[pattern_pos];
      val value = expr.substr(expr_pos, end - expr_pos + 1);
      val result = match(expr, end + 1, pattern, pattern_pos + 1, { variable: value, __proto__: known_vars };
      ```
    * Если результат сопоставления успешен, его и возвращаем:
      ```javascript
      if (result.ok)
          return result;
      ```
    * Иначе смещаем `end` на начало следующего терма:
      * увеличиваем `end` на `1`,
      * если теперь `end == expr.len || expr[end] == ')'` — сопоставление невозможно (`return { ok: false };`),
      * если теперь `end` указывает на открывающую скобку, переставляем `end` на парную ей закрывающую (сами напишете).

Функция `match` стартует с состояния `match(expr, 0, pattern, 0, {})` — выражение и образец читаем с начала, ни одну переменную не знаем.

Отладка
======
В окне должна быть кнопка «Сопоставить», которая
* выполняет лексический и синтаксический анализ поля программы и поля зрения — если ошибки есть, сообщает о них и дальше ничего не делает,
* берёт из поля зрения первый образец первого предложения,
* берёт из поля программы первичное активное подвыражение,
* вызывает `let result = match(…)` для них,
* результат добавляет в конец `<body>`:
  ```javascript
  for (var in result)
      document.body += '<p>' + var + ' : ' + result[var] + '</p>';
  ```

Pull request по этой заявке должен добавлять работающую кнопку «Сопоставить».

Как и в других задачах, эту отладочную кнопку мы удалим на самом последнем этапе.

**Comment by Mazdaywik** [comment]
Так жестоко алгоритм сопоставления с образцом я не упрощал. @TonitaN, нет ли явных косяков в описании?

**Comment by TonitaN** [comment]
Если дочитано что-то одно, алгоритм не обязан выдавать неуспех, т.к. в хвосте образца могут быть ещё сопоставляемые с пустым словом е-переменные. Причём они могут быть в любом количестве, и как defined, так и undefined к моменту прочтения. Мне кажется, в этом случае имеет смысл всё же не делать полный перебор, а тупо проверить хвост образца на то, что там нет ничего, кроме undefined-е-переменных и е-переменных, уже получивших значение, равное empty.

**Comment by Mazdaywik** [comment]
Верное замечание, спасибо, сейчас поправлю.

Вариант с проверкой хвоста — оптимизация, а оптимизации у нас пока не приоритетны.

**UPD:** поправил.

**Comment by TonitaN** [comment]
На мой взгляд, это рассмотрение специального базисного случая рекурсии, а не основной (рекурсивной) части алгоритма, поэтому вполне допустимо сразу породить подстановки в пустые слова. Но если кажется, что для Петроса будет слишком сложно, то спорить не буду.

**Comment by Mazdaywik** [comment]
_(ответ на удалённый комментарий)_

Думаю, что не так уж и сложно, просто в приоритете получить работающее решение, не отвлекаясь на попутные улучшения.

Использование строк для представления поля зрения и так чудовищно неэффективно, поэтому добавлять мелкие оптимизации вроде случая `pattern_pos == pattern.length - 1 && pattern[pattern_pos].length == 2 && pattern[pattern_pos][0] == 'e'` (это означает, что мы в конце образца и образец заканчивается на e-переменную) в целом бессмысленно. Предполагается, что все примеры там будут короткими, образцы в примерах не слишком сложными, поэтому на производительности это заметно не скажется.

У меня задумка сделать этот интерпретатор как учебник, где каждый урок демонстрирует сначала очередное выразительное средство Рефала (скобки конкретизации, e- и s-переменные, структурные скобки и t-переменные, мощь образцов и т.д.), а затем, какую красоту можно на Рефале описать, например, арифметические операции, символьное вычисление производной.

<details><summary>Двоичные сложение и умножение в Крошечном Рефале</summary>

```
ex 0 + ey 0 = <ex + ey> 0
ex 0 + ey 1 = <ex + ey> 1
ex 1 + ey 0 = <ex + ey> 1
ex 1 + ey 1 = <<ex + ey> + 1> 0
 + ey = ey
ex +  = ex

ex 0 * ey = <ex * ey> 0
ex * ey 0 = <ex * ey> 0
ex 1 * ey = <<ex 0 * ey> + ey>
ex *  =
 * ey =
```

</details>

<details><summary>Десятичные сложение и вычитание в Крошечном Рефале</summary>

```
# Считаем в натуральных числах, отрицательных чисел нет.

# Инкремент и декремент
ex 9 ↑ = <ex↑> 0
ex sy↑ = <ex sy (0123456789)↑>
ex sy (e1 sy sn e2)↑ = ex sn
↑ = 1

ex 0 ↓ = <ex ↓> 9
ex sy↓ = <ex sy (0123456789)↓>
ex sy (e1 sp sy e2)↓ = ex sp

# Сложение
ex sx + ey 0 = <ex + ey> sx
ex 0 + ey sy = <ex + ey> sy
ex +  = ex
 + ey = ey
ex + ey = <<ex↑> + <ey↓>>

# Вычитание
ex sy - ey 0 = <ex - ey> sy
ex -  = ex
ex - ey = <<ex↓> - <ey↓>>
```

</details>

А вычисление производной знают все рефальщики, писать не буду.

**Comment by TonitaN** [comment]
Примеры красивые! Кстати, по декременту получается, что <10 ↓> = <1 ↓> 9 = 09, а значит, <<9 ↑> ↓> = 09, то есть декремент перестаёт быть левым обратным элементом к инкременту в алгебре арифметических операций. Вроде, по вычислениям результат всё равно правильный получается, но интересно, так было и задумано?

**Comment by Mazdaywik** [comment]
В примерах красиво то, что в них нет привычных нам функций. Обычно в Рефале за открывающей скобкой пишется имя функции, но на самом деле это не более чем оптимизация. Вообще, идеи Рефала нужно читать здесь:

* [В. Ф. Турчин. Программирование на языке РЕФАЛ. I. Неформальное введение в программирование на языке рефал. M.: ИПМ АН СССР, Препринт №41 за 1971 г., 55 с.](https://pat.keldysh.ru/~roman/doc/Turchin/1971-Turchin--Programmirovanie_na_yazyke_refal_1_Neformal'noe_vvedenie_v_programmirovanie_na_yazyke_refal.pdf)

Точно такие же оптимизации — символы-числа и составные символы. И их тоже нет в Крошечном Рефале — их можно выкинуть, и при этом Рефал останется Рефалом. А вот e-переменные выкинуть нельзя, поэтому они есть.

-------

Нет, не было задумано. Правильный декремент:

```
10↓ = 9
ex 0 ↓ = <ex ↓> 9
ex sy↓ = <ex sy (0123456789)↓>
ex sy (e1 sp sy e2)↓ = ex sp
```

Кстати, я забыл, что в описании языка в левых частях окружающие угловые скобки не ставятся. И обновил их в предыдущем комментарии.

**Comment by Mazdaywik** [comment]
Всё-таки напишу вычисление производной с одновременной оптимизацией

```
dsx/dsx = 1
d(tx + ty)/dsx = <<dtx/dsx> + <dty/dsx>>
d(tx * ty)/dsx = <<<dtx/dsx> * ty> + <tx * <dty/dsx>>>
dtc/dsx = 0

tx + 0  = tx
 0 + ty = ty
tx + ty = (tx + ty)

tx * 0  = 0
 0 * ty = 0
tx * 1  = tx
 1 * ty = ty
tx * ty = (tx * ty)
```

Расписывать вычитание и деление мне лень, хотя всё и так должно быть понятно.

**Comment by Mazdaywik** [comment]
Сделано в #11.
